require "bundler/setup"
require "cloudformation-ruby-dsl/cfntemplate"
require "cloudformation-ruby-dsl/spotprice"
require "cloudformation-ruby-dsl/table"
require_relative "mappings"
require_relative "parameters"
require_relative "helpers"
